### ISSUE TITLE
UnhandledPromiseRejectionWarning: TransformError

### ISSUE THREAD

**Issue by sideshowbarker** [goorockey/node-wechat-terminal#13]
After installing wechat-terminal from the npm package, it works for me fine but at startup and after other events, the following occasionally gets reported:

```
(node:83396) UnhandledPromiseRejectionWarning: TransformError: 1
    at new TransformError (/usr/local/lib/node_modules/node-wechat-terminal/node_modules/request-promise/lib/errors.js:50:15)
    at /usr/local/lib/node_modules/node-wechat-terminal/node_modules/request-promise/lib/rp.js:91:37
    at tryCatcher (/usr/local/lib/node_modules/node-wechat-terminal/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/node-wechat-terminal/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/node-wechat-terminal/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/node-wechat-terminal/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/node-wechat-terminal/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/usr/local/lib/node_modules/node-wechat-terminal/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/node-wechat-terminal/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/node-wechat-terminal/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/node-wechat-terminal/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:443:21)
(node:83396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:83396) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Umryuan** [comment]
I have a similar problem:
```
(node:913) UnhandledPromiseRejectionWarning: TransformError: 1   
```

**Comment by tzc123** [comment]
+1
