### ISSUE TITLE
RequestError: Error: incorrect header check

### ISSUE THREAD

**Issue by admk** [goorockey/node-wechat-terminal#4]
Version 0.1.5
`wechat-terminal` fails to launch and produces the following stack trace:

```
error:  RequestError: Error: incorrect header check
    at new RequestError (/usr/local/lib/node_modules/node-wechat-terminal/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/node-wechat-terminal/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/usr/local/lib/node_modules/node-wechat-terminal/node_modules/request/request.js:200:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Inflate.<anonymous> (/usr/local/lib/node_modules/node-wechat-terminal/node_modules/request/request.js:991:12)
    at emitOne (events.js:101:20)
    at Inflate.emit (events.js:188:7)
    at Zlib._handle.onerror (zlib.js:373:10)
```

**Comment by goorockey** [comment]
Which step did this error occur? Would you show me all the message. Something like:

> info: Scan above qrcode using mobile wechat.
> info: Waiting for scan...
> info: QRCode is scanned.
> error: Failed to init. Please try again.

**Comment by goorockey** [comment]
And it helps if you show your version of nodejs.

**Comment by goorockey** [comment]
I found this error happened with request@2.72.0, and it works fine with request@2.71.0. 
I adjust the package.json and make request@2.71.0 to be installed.
Reinstall your package and it should work fine.

**Comment by admk** [comment]
Thanks! I can confirm this change fixed the issue.
