### ISSUE TITLE
Why login failed?

### ISSUE THREAD

**Issue by iphyer** [goorockey/node-wechat-terminal#6]
Error Information.

`error: Failed to login.
error:  StatusCodeError: 404 - ""
    at new StatusCodeError (/usr/lib/node_modules/node-wechat-terminal/node_modules/request-promise/lib/errors.js:32:15)
    at /usr/lib/node_modules/node-wechat-terminal/node_modules/request-promise/lib/rp.js:70:37
    at tryCatcher (/usr/lib/node_modules/node-wechat-terminal/node_modules/request-promise/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/node-wechat-terminal/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/node_modules/node-wechat-terminal/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/usr/lib/node_modules/node-wechat-terminal/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/usr/lib/node_modules/node-wechat-terminal/node_modules/request-promise/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/usr/lib/node_modules/node-wechat-terminal/node_modules/request-promise/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/node-wechat-terminal/node_modules/request-promise/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)`

**Comment by liangli2718** [comment]
same problem here.

**Comment by ex172000** [comment]
same here

**Comment by rfma** [comment]
what's the matter? i got same question, then i debugged, when call _webwxnewloginpage function, the request get the 404 error response. But i access the url in my firefox browser, then get in . Maybe some parameters not valid ?  Anyone know ?

**Comment by ex172000** [comment]
It's because there's a 301 redirect. The program did not handle that redirect as good as the browser. This seems to be a underlying library issue.

**Comment by ysFengLi** [comment]
Request header Host, but  not host

**Comment by ysFengLi** [comment]
Request header Host, but  not host

**Comment by spaghett1c0de** [comment]
Same issue here.

**Comment by charnley** [comment]
same problem here

**Comment by rlp10** [comment]
I have the same problem. I presume there's no workaround at the moment. Shame, because this package looked good.

**Comment by iphyer** [comment]
It seems this problem continues comes but no solution offered. So I close this issue to be completed. Nearly 6 months passed.
